package com.connecteamed.server.domain.contribution.enums;

public enum ContributionAction {
    TASK_CREATE, TASK_UPDATE, TASK_DELETE,
    MEETING_CREATE, MEETING_UPDATE, MEETING_DELETE,
    TEAM_CREATE, TEAM_UPDATE, TEAM_DELETE,
    DOCUMENT_CREATE, DOCUMENT_UPDATE, DOCUMENT_DELETE,
    COMPLETED_TASK_UPDATE, COMPLETED_TASK_DELETE,
    RETROSPECTIVE_CREATE, RETROSPECTIVE_UPDATE, RETROSPECTIVE_DELETE;
}
