spring:
  application:
    name: connecteamed-be

  profiles:
    active: notLocal

  data:
      redis:
        host: localhost
        port: 6379
        password: ${REDIS_PASSWORD}


  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/connecteamed_db}
    username: ${SPRING_DATASOURCE_USERNAME:connecteamed}
    password: ${SPRING_DATASOURCE_PASSWORD:connecteamed}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false
  
  output:
    ansi:
      enabled: ALWAYS

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - account_email
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오 유저 고유번호

jwt:
  token:
    secretKey: ${JWT_SECRET_KEY}
    expiration:
      access: 14400000
      refresh: 1209600000


springdoc:
  swagger-ui:
    # Swagger UI 접속 경로를 /docs로 변경
    # http://localhost:8080/docs 로 접속
    path: /docs

server:
  port: 8080
  forward-headers-strategy: framework
app:

  oauth2:
    frontend-redirect-url: ${FRONTEND_REDIRECT_URL}


  s3:
    region: ${APP_S3_REGION:ap-northeast-2}
    bucket: ${APP_S3_BUCKET}
    access-key: ${APP_S3_ACCESS_KEY}
    secret-key: ${APP_S3_SECRET_KEY}

  # Test Configuration
  test:
    login-id: ${TEST_LOGIN_ID:test@example.com}
    user-name: ${TEST_USER_NAME:테스트사용자}

logging:
  exception-conversion-word: "%wEx{0}"
